pipeline {
    agent any

    stages {
        stage('Install') {
            steps {
                sh 'npm install'
            }
        }
        stage('Build') {
            steps {
                sh 'npm run build || echo "No build step needed"'
            }
        }
        stage('Test') {
            steps {
                sh 'npm test'
            }
        }
    }
}
