trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '16.x'
  displayName: 'Install Node.js'

- script: |
    npm install
  displayName: 'Install Dependencies'

- script: |
    npm test
  displayName: 'Run Tests'

- task: SonarCloudPrepare@1
  inputs:
    SonarCloud: 'SonarCloudConnection'
    organization: 'vineeth157777'
    scannerMode: 'CLI'
    configMode: 'manual'
    cliProjectKey: 'azure-devops-migration-project'
    cliProjectName: 'azure-devops-migration-project'
    extraProperties: |
      sonar.login=$(SonarCloudToken)  # 🔐 Inject the token from Key Vault

- script: |
    sonar-scanner -Dproject.settings=sonar/sonar-project.properties
  displayName: 'Run SonarCloud Analysis'

- task: SonarCloudPublish@1
  inputs:
    pollingTimeoutSec: '300'

- script: |
    sonar-scanner -Dproject.settings=sonar/sonar-project.properties
  displayName: 'Run SonarQube Analysis'

- task: SonarCloudPublish@1
  inputs:
    pollingTimeoutSec: '300'
