trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '16.x'
  displayName: 'Install Node.js'

- script: |
    npm install
  displayName: 'Install Dependencies'

- script: |
    npm test
  displayName: 'Run Tests'

# Prepare SonarCloud Analysis
- task: SonarCloudPrepare@1
  inputs:
    SonarCloud: 'SonarCloudConnection'  # Make sure this service connection exists
    organization: 'vineeth157777'
    scannerMode: 'CLI'
    configMode: 'manual'
    cliProjectKey: 'azure-devops-migration-project'
    cliProjectName: 'azure-devops-migration-project'

# Run SonarCloud Analysis using project properties
- script: |
    sonar-scanner -Dproject.settings=sonar/sonar-project.properties
  displayName: 'Run SonarCloud Analysis'

# Publish SonarCloud Results
- task: SonarCloudPublish@1
  inputs:
    pollingTimeoutSec: '300'
